chatbot/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .views import UserEditView, UserProfileEditView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),

    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),


    path('edit_user/', UserEditView.as_view(), name='edit_user'),
    path('edit_profile/', UserProfileEditView.as_view(), name='edit_profile'),
    path('edit_mood/', views.edit_mood, name='edit_mood'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('password/', ChangePasswordView.as_view(), name='set_password'),
]

chatbot/chatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('', include(('home.urls', 'home'), namespace='home')),
                  path('admin/', admin.site.urls),

                  path('auth/', include(('accounts.urls', 'accounts'), namespace='auth')),

                  path('chats/', include(('chats.urls', 'chats'), namespace='chats')),

                  path('reset_password/', auth_views.PasswordResetView.as_view(
                      template_name='accounts/password_reset.html',
                  ), name='reset_password'),
                  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
                      template_name='accounts/password_reset_done.html',
                  ), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      # template_name='accounts/password_reset_confirm.html',
                  ), name='password_reset_confirm'),
                  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='accounts/password_reset_complete.html',
                  ), name='password_reset_complete'),

                  path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
                  path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
                  path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatbot/chats/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path(
        "",
            include(
                [
                    path("list/", views.ChatFilterView.as_view(), name="chat_list"),
                    path("detail/<int:pk>/", views.ChatDetailView.as_view(), name="chat_detail"),
                    path("public/detail/<int:pk>/", views.PublicChatDetailView.as_view(), name="public_chat_detail"),
                    path("delete/", views.chat_delete, name="chat_delete"),
                    path('add_message/', views.add_message, name='add_message'),
                    path('create_chat/', views.create_chat, name='create_chat'),
                    path('change-private/', views.change_private, name='change_private'),
                    path('add_comment/', views.add_comment, name='add_comment'),
                ]
            ),
    ),
]

chatbot/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('licensing/', views.licensing_view, name='licensing'),
    path('privacy/', views.privacy_view, name='privacy'),
]

chatbot/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        app_label = 'accounts'
        permissions = [('change_password', 'Can change password')]

    def __str__(self):
        return f'{self.username}'


class Profile(models.Model):
    user = models.OneToOneField(User, null=True , on_delete=models.CASCADE)

    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='images/profiles/', default='https://xsgames.co/randomusers/avatar.php?g=pixel')
    birthdate = models.DateField(null=True, blank=True)
    emotion = models.CharField(max_length=100, blank=True, default="neutral")
    location = models.CharField(max_length=100, blank=True)
    language = models.CharField(max_length=100, blank=True)




    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        # super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.user}'

chatbot/accounts/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from allauth.account.forms import LoginForm, SignupForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User


class UserLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['login'].widget = forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Enter Username', 'id': 'username'})
        self.fields['password'].widget = forms.PasswordInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Enter Password', 'id': 'password'})
        self.fields['remember'].widget = forms.CheckboxInput(attrs={'class': 'form-check-input'})


class UserRegistrationForm(SignupForm):

    # Redéfinir l'ordre des champs dans le formulaire
    field_order = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.fields['username'].widget = forms.TextInput(attrs={'class': 'form-control mb-1', 'placeholder': 'Entrez un nom d\'utilisateur', 'id': 'username1'})
        self.fields['password1'].widget = forms.PasswordInput(attrs={'class': 'form-control textInput', 'placeholder': 'Entrez un mot de passe', 'id': 'password1'})
        self.fields['password2'].widget = forms.PasswordInput(attrs={'class': 'form-control textInput', 'placeholder': 'Confirmez votre mot de passe', 'id': 'password2'})
        self.fields['password2'].label = "Confirmez votre mot de passe"
        
        
        

class EditUserForm(UserChangeForm):
    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 
                'placeholder': 'Enter Email', 
                'id': 'email'
            }))    
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500',
                'placeholder': 'Enter Username',
                'id': 'username'
            }))
    first_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 
                'placeholder': 'Enter First Name', 
                'id': 'first_name'
            }))
    last_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', 
                'placeholder': 'Enter Last Name', 
                'id': 'last_name'
            }))

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        exclude = [ 'is_active', 'is_staff', 'is_superuser', 'last_login', 'date_joined']

chatbot/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from .forms import UserRegistrationForm, UserLoginForm, EditUserForm
from .models import Profile, User

from chats.models import Chat


def register_view(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(request)
            
            Profile.objects.create(user=user)
            
            messages.success(request, f'Account created for {form.cleaned_data["username"]}')

    else:
        form = UserRegistrationForm()
    return render(request, "accounts/register.html", {"form": form})


class login_view(generic.FormView):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('home:home')
    
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)
    
    def form_invalid(self, form):
        error_messages = ''
        for field, errors in form.errors.items():
            for error in errors:
                error_messages += f"{field}: {error}\n"
        messages.error(self.request, error_messages)
        return super().form_invalid(form)


def logout_view(request):
    logout(request)
    return redirect('home:home')



class UserEditView(generic.UpdateView):
    form_class = EditUserForm
    template_name = 'accounts/edit_user.html'
    success_url = reverse_lazy('auth:edit_user')
    
    def get_object(self):
        return self.request.user
    
    
class UserProfileEditView(generic.UpdateView):
    model = Profile
    fields = ['bio', 'avatar', 'birthdate', 'emotion', 'location', 'language']
    template_name = 'accounts/edit_profile.html'
    success_url = reverse_lazy('auth:edit_profile')
    
    # success_url = '/edit_profile'
    
    def form_valid(self, form):
        print("form_valid", form)
        if form.is_valid():
            self.object = form.save()
            messages.success(self.request, f'Profile updated for {self.request.user}')
            return super().form_valid(form)
        else:
            # Log form errors
            print(form.errors)
            return self.form_invalid(form)
    
    def get_object(self, queryset=None):
        profile, created = Profile.objects.get_or_create(user=self.request.user)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['languages'] = [
            {'code': 'us', 'name': 'English'},
            {'code': 'es', 'name': 'Spanish'},
            {'code': 'fr', 'name': 'French'},
            {'code': 'de', 'name': 'German'},
        ]
        return context


def profile_view(request, username):
    template_name = 'accounts/profile.html'
    context = {}

    user = User.objects.get(username=username)

    context['user_data'] = user

    datas_chats = []
    chats = Chat.objects.filter(user=user, is_private=False)
    for chat in chats:
        datas_chats.append({
            'id': chat.id,
            'name': chat.name,
            'created_at': chat.created_at,
        })

    context['datas_chats'] = datas_chats

    return render(request, template_name, context)

def edit_mood(request):
    if request.method == "POST":
        user = request.user
        profile = Profile.objects.get(user=user)
        profile.emotion = request.POST['emotion']
        profile.save()
        messages.success(request, f'Mood updated to {profile.emotion}')
        return redirect('home:home')
    else:
        return redirect('home:home')

class ChangePasswordView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy("user_profile")

    def post(self, request, *args, **kwargs):
        old_password: str = request.POST.get("old_password")
        new_password1: str = request.POST.get('new_password1')
        new_password2: str = request.POST.get('new_password2')

        user = request.user

        if not user.check_password(old_password):
            messages.warning(request, "old password doesn't match.")
            return redirect("auth:password")

        if len(new_password1) < 10:
            messages.warning(request, "password length should not be less than 10.")
            return redirect("auth:password")

        if old_password == new_password1:
            messages.warning(request, "your new password cannot be the same as your old password.")
            return redirect("auth:password")

        if new_password1 != new_password2:
            messages.warning(request, "new_password1 and new_password2 do not match.")
            return redirect("auth:password")

        user.set_password(new_password1)
        user.save()
        update_session_auth_hash(request, user)
        messages.success(request, "password change successfull. your new password would take effect on next login.")
        logout(request)

        return redirect("auth:login")

chatbot/templates/accounts/edit_profile.html
{% extends 'base.html' %}{% load static %}
{% block title %}
  Edit Profile
{% endblock %}

{% block content %}
  <section class="pt-4 bg-gray-50 dark:bg-gray-900">
    <div class="px-6 py-8 mx-auto lg:py-0 container">
      <div class="bg-white rounded-lg shadow dark:border md:mt-0 xl:p-0">
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
          <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl">Profile</h1>

          <form class="space-y-4 md:space-y-6" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% comment %} {{ form.as_p }} {% endcomment %}
            <div class="grid gap-4">
              {% comment %} {{ form.as_p }} {% endcomment %}

              {% comment %} if picture display {% endcomment %}
              {% if form.avatar.value %}
                <div>
                  {% load dict_filter %}
                  <img src="{{ form.avatar.value.url|remove_media_prefix }}" alt="avatar" class="w-20 h-20 rounded-full" />
                </div>
              {% endif %}

              <div>
                <label for="avatar" class="block mb-2 text-sm font-medium text-gray-900">Avatar</label>
                <input type="file" name="avatar" accept="image/*" id="id_avatar" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400" />
              </div>

              <div>
                <label for="bio" class="block mb-2 text-sm font-medium text-gray-900">Description</label>
                <textarea id="id_bio" name="bio" rows="4" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Write something about you here...">{{ form.bio.value }}</textarea>
              </div>

              <div>
                <label for="birthdate" class="block mb-2 text-sm font-medium text-gray-900">Birthdate</label>
                <input value="{{ form.birthdate.value|date:"Y-m-d" }}" type="date" name="birthdate" id="id_birthdate" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="" />
              </div>

              {% comment %} Mood Selector {% endcomment %}
              <div>
                <label for="emotion" class="block mb-2 text-sm font-medium text-gray-900">Actual mood</label>
                <select name="emotion" id="id_emotion" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                  <option value="happy" {% if form.emotion.value == "happy" %} selected {% endif %}>🙂 Happy</option>
                  <option value="sad" {% if form.emotion.value == "sad" %} selected {% endif %}>😭 Sad</option>
                  <option value="angry" {% if form.emotion.value == "angry" %} selected {% endif %}>😡 Angry</option>
                  <option value="neutral" {% if form.emotion.value == "neutral" %} selected {% endif %}>😐 Neutral</option>
                  <option value="I don't care" {% if form.emotion.value == "I don't care" %} selected {% endif %}>🖕 I don't care</option>
                </select>
              </div>
              {% comment %} End Mood Selector {% endcomment %}

              {% comment %} Langauge Selector {% endcomment %}
              <div>
                <label for="language" class="block mb-2 text-sm font-medium text-gray-900">Default language four output of ChatGPT</label>
                <input type="hidden" id="id_language" name="language" value="{{form.language.value}}">
                <div class="relative dropdown-container bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <div class="dropdown-selected p-2.5 cursor-pointer flex items-center">Choisissez une langue</div>
                  <div class="dropdown-options hidden absolute bg-white dark:bg-gray-700 border mt-1 rounded-lg w-full z-10">
                      {% for language in languages %}
                        <div class="dropdown-option p-2.5 cursor-pointer flex items-center" data-value="{{ language.code }}">
                          <img src="/static/country-flags/png100px/{{ language.code|lower }}.png" alt="" class="h-3.5 w-3.5 rounded-full mr-2"> {{ language.name }}
                        </div>
                      {% endfor %}
                  </div>
                </div>
              </div>
              {% comment %} End Languge Selector {% endcomment %}

            </div>

            <div class="text-end">
              <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Update</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block extra_js %}
  <script src="{% static "js/language_selector.js" %}" ></script>
{% endblock %}

chatbot/templates/accounts/edit_user.html
{% extends 'base.html' %}
{% block title %}
    Edit Profile
{% endblock %}

{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0  xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    {% for message in messages %}
                        {% if forloop.last %}
                            <div class="alert {{ message.tags }} border-l-4 p-4">
                                <p>{{ message }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Settings</h1>

                    <form class="space-y-4 md:space-y-6" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="grid lg:grid-cols-2 gap-4 grid-cols-1">
                            <div>
                                <label for="username"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                                {{ form.username }}
                            </div>

                            <div>
                                <label for="email"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Email</label>
                                {{ form.email }}
                            </div>
                        </div>

                        <div class="grid lg:grid-cols-2 grid-cols-1 gap-4">
                            <div>
                                <label for="first_name"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">First name</label>
                                {{ form.first_name }}
                            </div>

                            <div>
                                <label for="last_name"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Last name</label>
                                {{ form.last_name }}
                            </div>
                        </div>


                        <button type="submit"
                                class="float-right text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            Save
                        </button>

                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            Want to set a new password ? <a href="{% url 'auth:set_password' %}"
                                                            class="font-medium text-primary-600 hover:underline dark:text-primary-500">Set
                            here</a>

                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


{% comment %}for each input chnage label{% endcomment %}
{% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }}
        {% comment %}<label for="{{ field.id_for_label }}"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ field.label }}</label> {% endcomment %}

        {{ field }}
    </div>
{% endfor %}

chatbot/templates/accounts/login.html
{% extends '../base.html' %}
{% block content %}

    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    {% for message in messages %}
                        {% if forloop.last %}
                            <div class="alert {{ message.tags }} border-l-4 p-4">
                                <p>{{ message }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            You are already logged in</h1>
                    {% else %}
                        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                            Login</h1>

                        <form class="space-y-4 md:space-y-6" action="{% url 'auth:login' %}?next=/" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.GET.next|default:'/' }}"/>

                            <div>
                                <label for="username"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Username</label>
                                <input type="text" name="username" id="id_username"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       placeholder="name@company.com" required=""/>
                            </div>

                            <div>
                                <label for="password"
                                       class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                                <input type="password" name="password" id="id_password" placeholder="••••••••"
                                       class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                                       required=""/>
                            </div>

                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                    <input id="id_remember" aria-describedby="remember" type="checkbox"
                                           class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800"/>
                                </div>
                                <div class="ml-3 text-sm">
                                    <label for="remember" class="font-light text-gray-500 dark:text-gray-300">Remember
                                        me</label>
                                </div>
                            </div>

                            <button type="submit"
                                    class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                                Log In
                            </button>
                            <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                                Don't have an account? <a href="{% url 'auth:register' %}"
                                                          class="font-medium text-primary-600 hover:underline dark:text-primary-500">Register
                                here</a>
                            </p>

                            <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                                Forgot your password? <a href="{% url 'reset_password' %}"
                                                         class="font-medium text-primary-600 hover:underline dark:text-primary-500">Reset
                                here</a>

                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

chatbot/templates/accounts/password_reset.html
{% extends 'base_empty.html' %}

{% block content %}

<section class="bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
        TheTrioLC™   
      </a>
      <div class="w-full p-6 bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md dark:bg-gray-800 dark:border-gray-700 sm:p-8">
          <h1 class="mb-1 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
              Forgot your password?
          </h1>
          <p class="font-light text-gray-500 dark:text-gray-400">Don't fret! Just type in your email and we will send you a code to reset your password!</p>
          <form class="mt-4 space-y-4 lg:mt-5 md:space-y-5" method="post">
            {% csrf_token %}
              <div>
                  <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
                  <input type="email" name="email" id="id_email" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@company.com" required="">
              </div>
              <button type="submit" class="w-full text-white bg-blue-600 hover:bg-blue-700 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Reset password</button>
          </form>
      </div>
  </div>
</section>
{% endblock %}