chatbot/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .views import UserEditView, UserProfileEditView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),

    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),


    path('edit_user/', UserEditView.as_view(), name='edit_user'),
    path('edit_profile/', UserProfileEditView.as_view(), name='edit_profile'),
    path('edit_mood/', views.edit_mood, name='edit_mood'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('password/', ChangePasswordView.as_view(), name='set_password'),
]

chatbot/chatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('', include(('home.urls', 'home'), namespace='home')),
                  path('admin/', admin.site.urls),

                  path('auth/', include(('accounts.urls', 'accounts'), namespace='auth')),

                  path('chats/', include(('chats.urls', 'chats'), namespace='chats')),

                  path('reset_password/', auth_views.PasswordResetView.as_view(
                      template_name='accounts/password_reset.html',
                  ), name='reset_password'),
                  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
                      template_name='accounts/password_reset_done.html',
                  ), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      # template_name='accounts/password_reset_confirm.html',
                  ), name='password_reset_confirm'),
                  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='accounts/password_reset_complete.html',
                  ), name='password_reset_complete'),

                  path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
                  path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
                  path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatbot/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('licensing/', views.licensing_view, name='licensing'),
    path('privacy/', views.privacy_view, name='privacy'),
]

chatbot/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        app_label = 'accounts'
        permissions = [('change_password', 'Can change password')]

    def __str__(self):
        return f'{self.username}'


class Profile(models.Model):
    user = models.OneToOneField(User, null=True , on_delete=models.CASCADE)

    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='images/profiles/', default='https://xsgames.co/randomusers/avatar.php?g=pixel')
    birthdate = models.DateField(null=True, blank=True)
    emotion = models.CharField(max_length=100, blank=True, default="neutral")
    location = models.CharField(max_length=100, blank=True)
    language = models.CharField(max_length=100, blank=True)




    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        # super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.user}'

chatbot/home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request, "home/home.html")

def about_view(request):
    return render(request, "home/about.html")

def licensing_view(request):
    return render(request, "home/licensing.html")

def privacy_view(request):
    return render(request, "home/privacy.html")

chatbot/templates/home/about.html
{% extends '../base.html' %}

{% block style %}
    <link rel="stylesheet" href="../static/css/home/about.css"/>
{% endblock %}

{% block title %}
    About page
{% endblock %}

{% block content %}
    <section class="bg-white dark:bg-gray-900">
        <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
            <h2 class="mb-8 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Frequently asked questions</h2>
            <div class="grid pt-8 text-left border-t border-gray-200 md:gap-16 dark:border-gray-700 md:grid-cols-2">
                <div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            What about us?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">we are 3 student developers for the LiveCampus school currently training to pass our state-recognized certification equivalent to BAC+4 :</p>
                        <p class="text-gray-500 dark:text-gray-400">- developer named <a href='https://github.com/LuckyMarty' class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline">Lucky Marty</a></p>
                        <p class="text-gray-500 dark:text-gray-400">- developer named <a href='https://github.com/TeyKz' class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline">Mathieu VIDOT</a></p>
                        <p class="text-gray-500 dark:text-gray-400">- developer named <a href='https://github.com/JonathanMrtn' class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline">Jonathan MARTIN</a></p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Why have done this website?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">We had a mission past weeks ago to do a functional website which use python and django onto framework to make an application which respond to some contraints of a website like ChatGPT have done.</p>
                        <p class="text-gray-500 dark:text-gray-400">We choose to developp a similar application like Chat GPT but with our personnal touch.</p>
                        <p class="text-gray-500 dark:text-gray-400">We also need, weeks after, to deploy and improve it to make it more powerful and responsive, we choose to enable a pulic and private parts of our site and more personnalisation into the communication with Chat-GPT by using agents.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Why use Python has primary language?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">First of all, because i was the constraint of the project by using Django</p>
                        <p class="text-gray-500 dark:text-gray-400">Second, because, it work very well for this project, this langage is really powerful to use Artificial Intelligence.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Why use Django to build this website?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">First of all, because i was the constraint of the project by using Django</p>
                        <p class="text-gray-500 dark:text-gray-400">Second, because, it sipmly work, it's easy to take and make models, views and templats (MVT).</p>
                    </div>
                </div>
                <div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            How we deploy it?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">We use <a href='https://www.pythonanywhere.com/' class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline">PythonAnyWhere</a> which permit to deploy it for free into the internet web page.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Could we improve the website by the report of community?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">YES ! We are open, to new personnalisation of your website, you can transmit by using our contact page and give us more information to add or imrove what's already done.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            What are our next projects?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">We gonna all return to our companies to make projects works like we done when we are not making project for LiveCampus but we are able to create a lot of other project which add skills to developp at IT.</p>
                        <p class="text-gray-500 dark:text-gray-400">You can see our <a href='https://github.com/LC-Projects' class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline">lastest projects</a> build for LiveCampus with different langage used an some technology with other frameworks.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

chatbot/templates/home/contact.html
{% extends '../base.html' %}


{% block style %}
    <link rel="stylesheet" href="../static/css/home/contact.css"/>
{% endblock %}

{% block title %}
    Contact Us
{% endblock %}

{% block content %}
    <br>
    <p><strong>If you have any questions or feedback, please feel free to contact us using the information below:</strong></p>
    <br><hr><br>
    <h2>Email</h2>
    <p>For general inquiries, please email us at: <a href="mailto:info@example.com">info@example.com</a></p>
    <br><hr><br>
    <h2>Phone</h2>
    <p>You can reach us by phone during our business hours at: <a href="tel:+1234567890">+1 (234) 567-890</a></p>
    <br><hr><br>
    <h2>Address</h2>
    <p>Visit us at our office at the following address:</p>
    <address>
        123 Example Street,<br>
        City, State, 12345
    </address>
    <br><hr><br>
    <h2>Social Media</h2>
    <p>Follow us on our social media pages:</p>
    <ul>
        <li><a href="https://www.facebook.com" target="_blank">Facebook</a></li>
        <li><a href="https://www.twitter.com" target="_blank">Twitter</a></li>
        <li><a href="https://www.instagram.com" target="_blank">Instagram</a></li>
    </ul>
    <br><hr><br>
    <br>
{% endblock %}

chatbot/templates/home/licensing.html
{% extends '../base.html' %}

{% block style %}
    <link rel="stylesheet" href="../static/css/home/licensing.css"/>
{% endblock %}

{% block title %}
    Licensing Information
{% endblock %}

{% block content %}
    <section class="bg-white dark:bg-gray-900">
        <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
            <h2 class="mb-8 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Licence of our website</h2>
            <div class="grid pt-8 text-left border-t border-gray-200 md:gap-16 dark:border-gray-700 md:grid-cols-2">
                <div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            More about ours licences?
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">This page provides information about the licensing of the content, software, and/or services provided through our website. Understanding the terms of use and the scope of the licenses granted is important for both users and contributors.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Content Licensing
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">Unless otherwise stated, the content on this website is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. This allows for the sharing and adaptation of the content provided that appropriate credit is given, and any changes are distributed under the same license as the original.</p>
                    </div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Third-Party Licenses
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">Some of the content, software, or services offered through our website may be owned by third parties and subject to different licenses. We endeavor to provide clear licensing information for such third-party materials and encourage users to review the licensing terms of any third-party resources.</p>
                    </div>
                </div>
                <div>
                    <div class="mb-10">
                        <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                            <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                            Questions and Contact Information
                        </h3>
                        <p class="text-gray-500 dark:text-gray-400">If you have any questions about the licensing of our content, software, or services, or if you require further information, please contact us at the provided contact details on our website.</p>
                    </div>
                </div>
                <div class="mb-10">
                    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                        Software Licensing
                    </h3>
                    <p class="text-gray-500 dark:text-gray-400">The software available on this website, unless specifically noted, is distributed under the MIT License. This permissive license allows for reuse within both commercial and non-commercial settings, provided that the license and copyright notice are included with any substantial portions of the software.</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

chatbot/templates/home/lobby.html
{% extends '../base.html' %}

{% block title %}
  Home page
{% endblock %}

{% block content %}
  <div class="bg-gradient-to-b from-gray-50 to-gray-100 w-full py-14">
      <div class="max-w-screen-xl px-8 xl:px-16 mx-auto" id="about">
      
        <div>
          <div class="grid grid-flow-row sm:grid-flow-col grid-rows-2 md:grid-rows-1 sm:grid-cols-2 gap-8 py-6 sm:py-16" style="opacity: 1; transform: none;">
      
            <div class="flex flex-col justify-center items-start row-start-2 sm:row-start-1">
              <h1 class="text-3xl lg:text-4xl xl:text-5xl font-medium text-black-600 leading-normal">
                    Want anything to be easy with <strong>ChatBot</strong>.
                </h1>
                <p class="text-black-500 mt-4 mb-6">
                    Provide a seamless experience for your customers with our chatbot. No more waiting for a response, get instant answers to your questions.
                </p>
            </div>
            
            <!-- Mood Form -->
            <div class="row-start-1 sm:row-start-1">
              <form action="{% url 'auth:edit_mood' %}" method="POST">
                {% csrf_token %}
                <label for="mood" class="block text-sm font-medium text-gray-700">How are you feeling today?</label>
                {% comment %} Mood Selector {% endcomment %}
                <div>
                  <label for="emotion" class="block mb-2 text-sm font-medium text-gray-900">Actual mood</label>
                  <select name="emotion" id="id_emotion" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    <option value="happy" {% if form.emotion.value == "happy" %} selected {% endif %}>🙂 Happy</option>
                    <option value="sad" {% if form.emotion.value == "sad" %} selected {% endif %}>😭 Sad</option>
                    <option value="angry" {% if form.emotion.value == "angry" %} selected {% endif %}>😡 Angry</option>
                    <option value="neutral" {% if form.emotion.value == "neutral" %} selected {% endif %}>😐 Neutral</option>
                    <option value="I don't care" {% if form.emotion.value == "I don't care" %} selected {% endif %}>🖕 I don't care</option>
                  </select>
                </div>
                {% comment %} End Mood Selector {% endcomment %}
                <button type="submit" class="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700">Submit</button>
              </form>
            </div>
            
          </div>
        </div>
      </div>
  </div>
{% endblock %}