chatbot/chatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('', include(('home.urls', 'home'), namespace='home')),
                  path('admin/', admin.site.urls),

                  path('auth/', include(('accounts.urls', 'accounts'), namespace='auth')),

                  path('chats/', include(('chats.urls', 'chats'), namespace='chats')),

                  path('reset_password/', auth_views.PasswordResetView.as_view(
                      template_name='accounts/password_reset.html',
                  ), name='reset_password'),
                  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
                      template_name='accounts/password_reset_done.html',
                  ), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      # template_name='accounts/password_reset_confirm.html',
                  ), name='password_reset_confirm'),
                  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='accounts/password_reset_complete.html',
                  ), name='password_reset_complete'),

                  path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
                  path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
                  path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatbot/feedback/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('contact/', views.FeedbackView.as_view(), name='contact'),
    path("list/", views.FeedbackFilterView.as_view(), name="feedback_list"),
    path("detail/<int:pk>/", views.FeedbackDetailView.as_view(), name="feedback_detail"),
    path("delete/<int:pk>/", views.delete_feedback, name="feedback_delete"),
]

chatbot/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('licensing/', views.licensing_view, name='licensing'),
    path('privacy/', views.privacy_view, name='privacy'),
]

chatbot/templates/_partials/footer.html
<footer class="bg-gray-50 dark:bg-gray-900 p-4">
    <div class="bg-white rounded-lg shadow dark:bg-gray-800">
      <div class="w-full mx-auto max-w-screen-xl p-4 md:flex md:items-center md:justify-between">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="https://github.com/LC-Projects/DjangoProject" class="hover:underline">TheTrioLC™</a>. All Rights Reserved.</span>
        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400 sm:mt-0">
          <li>
            <a href="{% url 'home:about' %}" class="hover:underline me-4 md:me-6">About</a>
          </li>
          <li>
            <a href="{% url 'home:privacy' %}" class="hover:underline me-4 md:me-6">Privacy Policy</a>
          </li>
          <li>
            <a href="{% url 'home:licensing' %}" class="hover:underline me-4 md:me-6">Licensing</a>
          </li>
          <li>
            <a href="{% url 'feedback:contact' %}" class="hover:underline">Contact</a>
          </li>
        </ul>
      </div>
    </div>
</footer>