chatbot/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .views import UserEditView, UserProfileEditView, ChangePasswordView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),

    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),


    path('edit_user/', UserEditView.as_view(), name='edit_user'),
    path('edit_profile/', UserProfileEditView.as_view(), name='edit_profile'),
    path('edit_mood/', views.edit_mood, name='edit_mood'),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('password/', ChangePasswordView.as_view(), name='set_password'),
]

chatbot/chatbot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('', include(('home.urls', 'home'), namespace='home')),
                  path('admin/', admin.site.urls),

                  path('auth/', include(('accounts.urls', 'accounts'), namespace='auth')),

                  path('chats/', include(('chats.urls', 'chats'), namespace='chats')),

                  path('reset_password/', auth_views.PasswordResetView.as_view(
                      template_name='accounts/password_reset.html',
                  ), name='reset_password'),
                  path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
                      template_name='accounts/password_reset_done.html',
                  ), name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
                      # template_name='accounts/password_reset_confirm.html',
                  ), name='password_reset_confirm'),
                  path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='accounts/password_reset_complete.html',
                  ), name='password_reset_complete'),

                  path('forum/', include(('forum.urls', 'forum'), namespace='forum')),
                  path('notification/', include(('notification.urls', 'notification'), namespace='notification')),
                  path('feedback/', include(('feedback.urls', 'feedback'), namespace='feedback')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chatbot/chats/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path(
        "",
            include(
                [
                    path("list/", views.ChatFilterView.as_view(), name="chat_list"),
                    path("detail/<int:pk>/", views.ChatDetailView.as_view(), name="chat_detail"),
                    path("public/detail/<int:pk>/", views.PublicChatDetailView.as_view(), name="public_chat_detail"),
                    path("delete/", views.chat_delete, name="chat_delete"),
                    path('add_message/', views.add_message, name='add_message'),
                    path('create_chat/', views.create_chat, name='create_chat'),
                    path('change-private/', views.change_private, name='change_private'),
                    path('add_comment/', views.add_comment, name='add_comment'),
                ]
            ),
    ),
]

chatbot/forum/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.AllForumsView, name="home"),
    path("<slug:slug>/", views.ForumByCategoryView, name="home_slug"),
]

chatbot/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('licensing/', views.licensing_view, name='licensing'),
    path('privacy/', views.privacy_view, name='privacy'),
]

chatbot/forum/models.py
from django.db import models

# Create your models here.

chatbot/forum/views.py
import datetime
from django.shortcuts import render
from django.urls import reverse

from chats.models import Chat, Category, Comment, Message

colors = ['red', 'blue', 'green', 'yellow', 'purple', 'orange', 'pink', 'cyan', 'teal', 'indigo', 'lime', 'gray', 'brown']
icons = {
    "general": '<i class="fa-solid fa-border-all"></i>',
    "recipes": '<i class="fa-solid fa-kitchen-set"></i>',
    "coding": '<i class="fa-solid fa-code"></i>',
    "entertainments": '<i class="fa-solid fa-trophy"></i>',
    "sports": '<i class="fa-solid fa-dumbbell"></i>',
    "news": '<i class="fa-solid fa-newspaper"></i>',
    "mathematics": '<i class="fa-solid fa-calculator"></i>',
}

# Create your views here.

def AllForumsView(request):
    template_name = 'forum/home.html'

    # TODO: Retrive all catergories, get the count of posts in each category and display them in the leftside bar
    public_chats = Chat.objects.filter(is_private=False)
    comments = Comment.objects.all()
    messages = Message.objects.filter(is_bot=False)


    # To get icons: https://fontawesome.com/search

    chats_datas = []
    for chat in public_chats:
        message = messages.filter(chat=chat).order_by('created_at').first()
        message_content = f"{message.content[:30]}..." if message else ''
        chat_data = {
            'id': chat.id,
            'title': chat.name,
            'author': chat.user.username,
            'date': combineDateAndAgo(chat.created_at.strftime('%Y-%m-%d')),
            'content': message_content,
            'comments': comments.filter(chat=chat).count(),
            # 'likes': chat.likes.count()
        }
        chats_datas.append(chat_data)
    context = {}
    context['leftside'] = displayCategory

    context['recipe'] = chats_datas

    return render(request, template_name, context)

def ForumByCategoryView(request, slug):
    template_name = 'forum/home.html'
    public_chats = Chat.objects.filter(is_private=False)
    public_chats_cat = public_chats.filter(category__slug=slug)
    comments = Comment.objects.all()
    messages = Message.objects.filter(is_bot=False)

    chats_datas = []
    for chat in public_chats_cat:
        message = messages.filter(chat=chat).order_by('created_at').first()
        message_content = f"{message.content[:30]}..." if message else ''
        chat_data = {
            'id': chat.id,
            'title': chat.name,
            'author': chat.user.username,
            'date': combineDateAndAgo(chat.created_at.strftime('%Y-%m-%d')),
            'content': message_content,
            'comments': comments.filter(chat=chat).count(),
            # 'likes': chat.likes.count()
        }
        chats_datas.append(chat_data)
    context = {}
    context['leftside'] = displayCategory

    context['recipe'] = chats_datas

    return render(request, template_name, context)


# UTILS FUNCTIONS
def displayCategory():
    categories = Category.objects.all()
    public_chats = Chat.objects.filter(is_private=False)

    categories_data = []
    categories_data.append(
        {
            'hr': True
        }
    )
    categories_data.append(
        {
            'color': 'white',
            'bg': 'red',
            'link': reverse('forum:home'),
            'icon': '<i class="fa-solid fa-border-all"></i>',
            'label': 'All',
            'count': public_chats.count()
        }
    )

    for category in categories:
        if public_chats.filter(category=category).count() == 0:
            continue

        color_index = category.id % len(colors)
        icon = icons.get(category.slug, '<i class="fa-solid fa-border-all"></i>')

        category_data = {
            'color': 'white',
            'bg': colors[color_index],
            'link': reverse('forum:home_slug', args=[category.slug]),
            'icon': icon  if icon else '<i class="fa-solid fa-border-all"></i>',
            'label': category.name,
            'count': public_chats.filter(category=category).count(),
            'slug': category.slug
        }
        categories_data.append(category_data)

    return categories_data



def convertDateToFrenchFormat(date):
    # 2021-09-01
    # 01/09/2021
    return date[8:] + '/' + date[5:7] + '/' + date[:4]


def TimeAgo(date):
    # 2021-09-01
    # until now

    date = datetime.datetime.strptime(date, '%Y-%m-%d')
    now = datetime.datetime.now()
    diff = now - date

    # Assuming diff is a datetime.timedelta object
    if diff.days >= 365.25:
        years = int(diff.days // 365.25)
        months = int((diff.days % 365.25) // 30.44)
        return f'{years} {"year" if years == 1 else "years"} and {months} {"month" if months == 1 else "months"} ago'
    elif diff.days >= 30.44:
        months = int(diff.days // 30.44)
        return f'{months} {"month" if months == 1 else "months"} ago'
    elif diff.days > 0:
        return f'{diff.days} {"day" if diff.days == 1 else "days"} ago'
    elif diff.seconds >= 3600:
        hours = diff.seconds // 3600
        return f'{hours} {"hour" if hours == 1 else "hours"} ago'
    elif diff.seconds >= 60:
        minutes = diff.seconds // 60
        return f'{minutes} {"minute" if minutes == 1 else "minutes"} ago'
    else:
        return f'{diff.seconds} {"second" if diff.seconds == 1 else "seconds"} ago'


def combineDateAndAgo(date):
    return convertDateToFrenchFormat(date) + ' (' + TimeAgo(date) + ')'

chatbot/home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
    return render(request, "home/home.html")

def about_view(request):
    return render(request, "home/about.html")

def licensing_view(request):
    return render(request, "home/licensing.html")

def privacy_view(request):
    return render(request, "home/privacy.html")

chatbot/templates/forum/home.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
  <div class="p-12 bg-gray-900">
      <h1 class="text-4xl font-bold text-white mx-auto text-center">Forum</h1>
  </div>
  <div class="p-12 bg-gray-900">
    <div class="grid block md:grid-cols-3 p-4 gap-12 container mx-auto">
      <div class="col-span-1">
        <div>
          <a href="{% url 'chats:chat_list' %}" class="block w-full text-center text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">Start a discussion</a>
        </div>

        <div class="flex flex-col gap-2">
          {% for item in leftside %}
            {% if item.hr %}
              <hr class="my-2 w-[80%] mx-auto" />
            {% else %}
              <a href="{{ item.link }}" class="inline-flex items-center justify-between gap-2 w-full px-5 py-2.5 text-sm font-medium text-center text-{{ item.color }} bg-{{ item.bg }}-400 rounded-lg hover:bg-{{ item.bg }}-500 focus:ring-4 focus:outline-none focus:ring-{{ item.bg }}-100 dark:bg-{{ item.bg }}-400 dark:hover:bg-{{ item.bg }}-600 dark:focus:ring-{{ item.bg }}-500">
                <div class="inline-flex gap-4">
                  <span class="w-4 h-4">{{ item.icon|safe }}</span>
                  <span>{{ item.label }}</span>
                </div>

                {% if item.count %}
                  <span class="inline-flex items-center justify-center w-4 h-4 ms-2 text-xs font-semibold text-gray-700 bg-white rounded-full">{{ item.count }}</span>
                {% endif %}
              </a>
            {% endif %}
          {% endfor %}
        </div>
      </div>

      {% if recipe %}
        <div class="col-span-2">
          <div class="flex flex-col gap-2">
              {% comment %} TODO: Display All; Display by Category {% endcomment %}
              {% for item in recipe %}
                <div class="bg-gray-700 shadow-md rounded-lg p-4 w-full">
                  <div class="flex items-center justify-between">
                    <div class="flex items-center gap-2 w-full">
                      <div class="w-10 h-10 bg-gray-300 rounded-full">
                          <img src="https://picsum.photos/100/100?random={{ forloop.counter }}" alt="category" class="w-full h-full object-cover rounded-full" />
                      </div>
                      <div>
                        <h2 class="text-lg font-semibold text-white">{{ item.title }}</h2>
                          <p class="text-gray-400">{{ item.content }}</p>
                        <p class="text-sm text-gray-500"><a class="text-sky-500 text-underline" href="{% url 'auth:profile' item.author %}">{{ item.author }}</a> - {{ item.date }}</p>
                      </div>
                    </div>

                    <div class="flex items-center gap-2">
                      <span class="inline-flex items-center justify-center gap-2 text-xs font-semibold text-red-500 bg-gray-700 rounded-full">{{ item.comments }} <i class="fa-solid fa-comment"></i></span>
                      {# <span class="inline-flex items-center justify-center gap-2 text-xs font-semibold text-red-500 bg-white rounded-full">{{ item.likes }} <i class="fa-solid fa-heart"></i></span>#}
                      <a href="{% url 'chats:public_chat_detail' item.id %}" class="text-white bg-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5">View</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
          </div>
        </div>
      {% else %}
      <div class="flex flex-col items-center justify-center">
        <div class="flex items center justify-between">
          <div class="flex items center">
              <span class="text-lg font-semibold text-gray-700 dark:text-gray-200">No channels yet. Please click on <a href="{% url 'chats:chat_list' %}" class="text-blue-500 hover:text-blue-700">Chats</a> to speak with GPT and make the discussion public to create one.</span>
          </div>
        </div>
        <div class="mt-4">
          <div class="flex items center">
              <span class="text-lg font-semibold text-gray-700 dark:text-gray-200">Share your discussion could help some user to affinate they talking to ChatGPT and have a better prompt answering to their response.</span>
          </div>
        </div>
        <div class="mt-4">
          <div class="flex items center">
              <span class="text-lg font-semibold text-gray-700 dark:text-gray-200">Users can help you too by sending some comments to your discussion to improve the question or correct the answer of ChatGPT which is not always the better you could get, community is the best tools you can contribute to be better.</span>
          </div>
        </div>
        <div class="mt-4">
          <div class="flex items center">
              <span class="text-lg font-semibold text-gray-700 dark:text-gray-200">Cordialy, <a href="https://github.com/LC-Projects/DjangoProject" class="text-blue-500 hover:text-blue-700">TheTrioLC</a>.</span>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
  </div>
{% endblock %}

chatbot/templates/forum/single.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
    <style>
        #forum-header {
            z-index: 0;
        }


        #forum-header::after {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            z-index: -1;
        }
    </style>


  <div class="text-white pt-12 pb-6 px-12 bg-gray-100 bg-[url('https://picsum.photos/1200/1200?random={{ id }}')] bg-no-repeat bg-cover bg-center relative" id="forum-header">
    <h1 class="mx-auto text-center text-white text-5xl">{{ data.title }}</h1>

    <div class="flex justify-between items-end mt-12">
        <div class="flex flex-col">
            <small>
                {{ data.author }}
            </small>
            <small>
                {{ data.date }}
            </small>
        </div>

        <div class="flex flex-inline gap-4">
            <small>
                {{ data.comments }} <i class="fa-solid fa-comment"></i>
            </small>

            <small>
                {{ data.likes }} <i class="fa-solid fa-heart"></i>
            </small>
        </div>
    </div>
  </div>

  <div class="grid block md:grid-cols-3 p-4 gap-12 container mx-auto"></div>
{% endblock %}